[project]
name = "src"
version = "0.0.1"
description = "An end to end MLOPS project with environment hazard prediction usecase"
authors = [{name = "Amrita Mandal", email = "amrita09091999@gmail.com"}]

[tool.setuptools] 
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}